function net = cnn_model()
% constructs matconvnet cnn model for mnibite dataset

net.layers = {};
net.layers = {end+1} = struct(...
    'name', 'conv1', ...
    'type', 'conv', ...
    'weights', {xavier(3, 3, 1, 3)});
net.layers = {end+1} = struct(...
    'name', 'conv2', ...
    'type', 'conv', ...
    'weights', {xavier(1, 1, 1, 3)});
net.layers = {end+1} = struct(...
    'name': 'loss', ...
    'type': 'l2normloss');

net.meta.inputSize = [394 466 1];
net.meta.trainOpts.learingRate = 0.001;
net.meta.trainOpts.numEpochs = 10;
net.meta.trainOpts.batchSize = 100;

net = vl_simplenn_tidy(net);

end
